#!/bin/bash -e

alias name1='syn1 tax1'
mkalias name1 '' command1
alias name2='syn2 tax2'
mkalias name2 '' command2
alias name3='syn3 tax3'
mkalias name3 '' command3

aliases="$(ALIAS)"
[ "${aliases}" = "alias name1='syn1 tax1'|alias name2='syn2 tax2'|alias name3='syn3 tax3'" ]

mkaliases="$(MKALIAS)"
[ "${mkaliases}" = "alias name1='syn1 tax1' (command1)|alias name2='syn2 tax2' (command2)|alias name3='syn3 tax3' (command3)" ]
