#!/bin/bash -e

mkalias name1 syntax1 command1
mkalias name2 syntax2 command2
mkalias name3 syntax3 command3

aliases="$(ALIAS)"
[ "${aliases}" = "alias name1='syntax1'|alias name2='syntax2'|alias name3='syntax3'" ]

mkaliases="$(MKALIAS)"
[ "${mkaliases}" = "alias name1='syntax1' (command1)|alias name2='syntax2' (command2)|alias name3='syntax3' (command3)" ]
