#!/bin/bash -e

mkalias name 'syn1 tax1' command1
mkalias name 'syn1 tax1' command1

aliases="$(ALIAS)"
[ "${aliases}" = "alias name='syn1 tax1'" ]
mkaliases="$(MKALIAS)"
[ "${mkaliases}" = "alias name='syn1 tax1' (command1)" ]

mkalias name 'syn2 tax2' command2

aliases="$(ALIAS)"
[ "${aliases}" = "alias name='syn2 tax2'" ]
mkaliases="$(MKALIAS)"
[ "${mkaliases}" = "alias name='syn2 tax2' (command2)" ]
